name: Using-Python-in-HPC
channels:
  - conda-forge
dependencies:
  - ipympl
  - ipywidgets
  - jupyterlab=2
  - matplotlib
  - nbresuse
  - numpy
  - scipy
  - pandas
  - python=3
  - psutil
  - astropy
  - beautifulsoup4=4.7.*
  - bokeh=1.0*
  - cloudpickle=0.8*
  - openblas
  - cython=0.29*
  - dask=1.1.*
  - dill=0.2*
  - h5py=2.9*
  - hdf5=1.10*
  - ipyparallel
  - jupyter_nbextensions_configurator
  - joblib
  - nb_conda
  - netCDF4
  - notebook=5.7.8
  - numba=0.42*
  - numexpr=2.6*
  - patsy=0.5*
  - prettytable
  - protobuf=3.7.*
  - pytables
  - scikit-image=0.14*
  - scikit-learn=0.20*
  - seaborn=0.9*
  - sqlalchemy=1.3*
  - statsmodels=0.9*
  - sympy=1.3*
  - tini=0.18.0
  - vincent=0.4.*
  - xlrd
  
